create table person (
                        id bigint not null,
                        creation_date timestamp(6),
                        email varchar(255),
                        name varchar(255),
                        password varchar(255),
                        role varchar(255),
                        primary key (id)
);



create table quote (
                       id bigint not null,
                       content varchar(255),
                       date_created timestamp(6),
                       date_updated timestamp(6),
                       person_id bigint,
                       primary key (id)
);



create table vote (
                      id bigint generated by default as identity,
                      created_at timestamp(6),
                      upvote boolean not null,
                      quote_id bigint,
                      user_id bigint,
                      primary key (id)
);



alter table if exists quote
    add constraint person_fk
        foreign key (person_id)
            references person;



alter table if exists vote
    add constraint quote_fk
        foreign key (quote_id)
            references quote;



alter table if exists vote
    add constraint user_fk
        foreign key (user_id)
            references person;

INSERT INTO PUBLIC.PERSON (ID, CREATION_DATE, EMAIL, NAME, PASSWORD, ROLE)
VALUES (10, '2023-02-12 18:28:42.000000', 'test@mail.ru', 'test',
        '$2a$12$p37p5gUZmV9ZkmSNmImD2ermx.y.yWybBvBpvMmodf7TNRj01v5/i', 'ADMIN');